/*  File src/init.c in package latentnet, part of the Statnet suite
 *  of packages for network analysis, http://statnet.org .
 *
 *  This software is distributed under the GPL-3 license.  It is free,
 *  open source, and has the attribution requirements (GPL Section 7) at
 *  http://statnet.org/attribution
 *
 *  Copyright 2003-2018 Statnet Commons
 */
/* This code was procedurally generated by running

   > tools::package_native_routine_registration_skeleton(".", "./src/init.c")

   in R started in the package's root directory, then adding #ifdef DEBUG / #endif around the P_alloc declarations.
*/

#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* .C calls */
extern void ERGMM_lp_Y_wrapper(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void ERGMM_MCMC_wrapper(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void klswitch_pK_wrapper(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void klswitch_step2_wrapper(void *, void *, void *, void *, void *, void *);
extern void klswitch_wrapper(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void MBC_MCMC_wrapper(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
#ifdef DEBUG
extern void P_free_all();
#endif // DEBUG
extern void post_pred_wrapper(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void procr_transform_wrapper(void *, void *, void *, void *, void *, void *, void *, void *);

static const R_CMethodDef CEntries[] = {
    {"ERGMM_lp_Y_wrapper",      (DL_FUNC) &ERGMM_lp_Y_wrapper,      20},
    {"ERGMM_MCMC_wrapper",      (DL_FUNC) &ERGMM_MCMC_wrapper,      65},
    {"klswitch_pK_wrapper",     (DL_FUNC) &klswitch_pK_wrapper,     12},
    {"klswitch_step2_wrapper",  (DL_FUNC) &klswitch_step2_wrapper,   6},
    {"klswitch_wrapper",        (DL_FUNC) &klswitch_wrapper,        13},
    {"MBC_MCMC_wrapper",        (DL_FUNC) &MBC_MCMC_wrapper,        20},
#ifdef DEBUG
    {"P_free_all",              (DL_FUNC) &P_free_all,               0},
#endif // DEBUG
    {"post_pred_wrapper",       (DL_FUNC) &post_pred_wrapper,       20},
    {"procr_transform_wrapper", (DL_FUNC) &procr_transform_wrapper,  8},
    {NULL, NULL, 0}
};

void R_init_latentnet(DllInfo *dll)
{
    R_registerRoutines(dll, CEntries, NULL, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
